### ISSUE TITLE
Horizon Constraints

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#367]
This is an umbrella issue for a number of things that can change with the horizon constraints:

- [ ] Account for entire Field of View #383 
- [ ] Determine how Altitude score should work #369 
- [ ] Test Altitude for entire time duration #365
- [ ] Horizon from image #364
- [ ] ~~Mark current image as obstructed (maybe via PAWS?) #392~~
- [x] ~~Potentially combine Altitude with Duration #366~~
- [x] Accepts lists instead of tuples #394
- [x] Read horizon info from config file #416

**Comment by jermainegug** [comment]
We can now tick off issue #394 :)

**Comment by wtgee** [comment]
I closed it as part of the merge, which is typically how you want to handle
it.
