### ISSUE TITLE
Config File Updates Overview

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#564]
* [ ] Add lots of documentation to config file to explain options.
* [x] ~~Rely on config file instead of env vars (#555).~~
* [ ] Ability to override individual nested keys.
  * [x] Via config server
  * [x] Via pocs_local.yaml file.
* [x] pyserial options #181 
* [x] Save config in local file #238 
* [x] issues with testing and config #259 
* [x] Target constraints in config #402 

Maybe:
* [x] ~~Have a directory config file in $PANDIR and a script for parsing (discussed in #555).~~
* [x] Add a `get_config_value('mount.serial.port')` that can be used to retrieve a single (nested) value, mostly for use in utility functions. _-or-_
* [x] Add a config query service.
* [x] ~~Convert config to [`ChainMap`](https://docs.python.org/3/library/collections.html#collections.ChainMap) rather than using a simple dict update. This allows for updates to underlying configs and easier overriding.~~
* [ ] Consider using the [pydantic Settings](https://pydantic-docs.helpmanual.io/usage/settings/) module.

Would be nice:
* [x] Web/notebook interface (https://github.com/panoptes/panoptes-tutorials/issues/48)
