### ISSUE TITLE
Observations Cleanup Overview

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#599]
PR #577 was an update to some of the google network connections to reflect usage on the running units as well as for use with PIAA when using google compute instances. However, that PR grew out of control so it is being split. Items to be accomplished

* [x] Properly document authentication routines. #600
* [x] Update google storage utilities. #601
* [x] Update google cloudsql access. #602
* [x] Run cloudsql proxy on startup. #626 

**Note:** based on review, some of the items have changed since we don't want to manage DB access. Checkboxes below reflect updates (some are not necessarily related to google network connections):

* [ ] Update the morning cleanup routines for each observation (or run-time?). ~~#628~~
  * [x] Remove cloudsql items. #652
  * [x] Update uploads to include manifest log. #654
  * [x] Timelapse and jpg options. #655
  * [x] Update cleanup script. #687 
  * [ ] Consider cleanup of upload scripts. https://github.com/panoptes/POCS/pull/654#discussion_r221798352
  * [x] Use CloudFunction endpoint for updating headers. https://github.com/panoptes/panoptes-network/pull/3
  * [ ] Consider more options for cleanup (timelapse on servers, etc).
  * [x] Make the image upload async. It currently can take a long time to upload images and it's very annoying to have to wait if for some reason you need to wait.

**Comment by wtgee** [comment]
Closing this as (mostly) complete. Additional development or ideas should have new Issues.
